### PR TITLE
Fix query builder search tests. Add test for NOTIMPLEMENTED types.

### PR DESCRIPTION
**Pull request by timgws**

### CODE REVIEW

**Comment by timgws** [comment]
@Chumper what is a good way to test the `getColumnFromName` function fully inside `QueryBuilderProvider`?

I am also working on some additional documentation for the QBP

**Comment by Chumper** [comment]
If it is not possible without ease i would also feel comfortable to let the coverage be below 100%

**Comment by timgws** [comment]
It will be a bit of a hack, but I will add a new class that uses a reflection to change the accessibility to public for this one function just so we can get that juicy 100% code coverage ;)

**Comment by Chumper** [comment]
At least you are committed to the 100% :)

**Pull request merged**
